### PR TITLE
Include support for Enhanced-R syntax

### PR DESCRIPTION
**Pull request by tomaskrehlik**
A lot of people use Enhanced-R plugin in the sublime text so might find it confusing that this plugin won't work with their set-up. It is also quite hard to debug, as the compiled binary does not provide much output.

### CODE REVIEW

**Comment by jimhester** [comment]
[Enhanced-R](https://github.com/randy3k/Enhanced-R) seems to be deprecated by the author in favor of [R-Box](https://github.com/randy3k/R-Box).  I do not use Sublime Text as my primary editor so am not aware of the common setups.

**Comment by tomaskrehlik** [comment]
Ah, interesting, did not know about that thanks for the link. Anyway, i think that adding the syntax tag won't hurt and there still might be some people using the old one, such as myself. :)

**Comment by jimhester** [comment]
Looks like you have a pyflake error that caused the build to fail.  You are missing a space after the comma on line 20 https://travis-ci.org/jimhester/SublimeLinter-contrib-lintr/builds/49878409#L114.  Once that is fixed I can merge this.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
